server.port=0
eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka
management.tracing.sampling.probability=1
management.endpoints.web.exposure.include=prometheus,health

#Risk scoring thresholds (sum of transaction item values)
risk.assessment.medium-risk-threshold=5000
risk.assessment.high-risk-threshold=10000
