server.port=8080
spring.datasource.url=jdbc:postgresql://transaction-api-postgres:5432/postgres
eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
spring.kafka.bootstrap-servers=notification-api-kafka:29092
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
spring.data.redis.host=redis

# Risk Score Properties
risk.score.value-weight=0.001
risk.score.item-weight=2
risk.score.max=100
risk.score.medium-threshold=40
risk.score.high-threshold=70
risk.score.block-threshold=90
